# Generated by Django 4.0.5 on 2022-06-28 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('imageUrl', models.URLField(default='github.com/luizAdamchuk.png')),
                ('newsSite', models.CharField(max_length=255)),
                ('summary', models.CharField(max_length=255)),
                ('publishedAt', models.DateField(default=datetime.date.today, verbose_name='publishedAt')),
                ('updatedAt', models.DateField(default=datetime.date.today, verbose_name='updatedAt')),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
