# Generated by Django 4.0.5 on 2022-06-28 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sfn', '0002_article_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('runAt', models.DateField(default=datetime.date.today, verbose_name='runAt')),
            ],
        ),
    ]
