# Generated by Django 4.0.5 on 2022-06-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sfn', '0003_cronjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='newsSite',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=2048),
        ),
    ]
