# Generated by Django 4.0.5 on 2022-06-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sfn', '0004_alter_article_newssite_alter_article_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='imageUrl',
            field=models.URLField(default='github.com/luizAdamchuk.png', max_length=2048),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(default='github.com/luizAdamchuk', max_length=2048),
        ),
    ]
