# Generated by Django 4.0.5 on 2022-06-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_sfn', '0005_alter_article_imageurl_alter_article_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='site_id',
            field=models.IntegerField(unique=True),
        ),
    ]
